"""add rank to news and comments

Revision ID: 6e3f4986ffdc
Revises: ac0c370e7236
Create Date: 2021-11-20 21:05:04.179948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3f4986ffdc'
down_revision = 'ac0c370e7236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('rank', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('news', 'rank')
    op.drop_column('comment', 'rank')
    # ### end Alembic commands ###
